# Fallback Matugen output (placeholder)
# matugen will overwrite this file.

$background = rgba(1a1b26FF)
$text_color = rgba(c0caf5FF)
$entry_background_color = rgba(1a1b2611)
$entry_border_color = rgba(3b426155)
$entry_color = rgba(7aa2f7FF)
$font_family = Rubik
$font_family_clock = Space Grotesk DemiBold
$font_material_symbols = Material Symbols Rounded

$background_image = ""
